Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projecto1.Models
{
    public class LoginViewModel
    {
        [Required]
        [DisplayName("E-mail")]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "El correo electrónico no es válido.")]
        public string Email_estudiante { get; set; }


        [Required]
        [DisplayName("Password")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$", ErrorMessage = "La contraseña no cumple con los requisitos, debe de tener mínimo 8 caracteres, al menos una letra minúscula, una letra mayúscula y un número.")]
        public string Password_estudiante { get; set; }
    }
}

Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Usuarios1Entities : DbContext
    {
        public Usuarios1Entities()
            : base("name=Usuarios1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}

Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\fidel\source\repos\Projecto1\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/sysdiagrams.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}

Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Projecto1.Models;
using System.Linq;
using System.Web.Security;


namespace Projecto1.Controllers
{
    public class AccountsController : Controller
    {
        Usuarios1Entities entity = new Usuarios1Entities();
        // GET: Accounts
        public ActionResult Login()
        {
            return View();
        }

        
        public ActionResult Signup()
        {
            return View();
        }

        public ActionResult RegistroMaterias()
        {
            return View();
        }




        [HttpPost]
        public ActionResult Login(LoginViewModel credentials)
        {
            
            bool userExist = entity.Estudiante.Any(x => x.Email_estudiante == credentials.Email_estudiante && x.Password_estudiante == credentials.Password_estudiante);
            Estudiante u = entity.Estudiante.FirstOrDefault(x => x.Email_estudiante == credentials.Email_estudiante && x.Password_estudiante == credentials.Password_estudiante);


            if (userExist)
            {
                FormsAuthentication.SetAuthCookie(u.Email_estudiante, false);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Hay algo que esta mal");
            return View();
        }

        [HttpPost]
        public ActionResult Signup(Estudiante userinfo)
        {
            entity.Estudiante.Add(userinfo);
            entity.SaveChanges();
            return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult RegistroMaterias(Materias userinfo2)
        {
            entity.Materias.Add(userinfo2);
            entity.SaveChanges();
            return RedirectToAction("Index","Home");
        }



        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projecto1.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Accounts/Login.cshtml
@model Projecto1.Models.LoginViewModel
<!DOCTYPE html>
<html>
<head>
    <title>Iniciar sesión</title>
    @{
        ViewBag.Title = "Iniciar sesión";
    }
    
<link href="~/Content/StyleSheet1.css" rel="stylesheet" />

    </head>
<body>
    <h2>Login</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>LoginViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Email_estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email_estudiante, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email_estudiante, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password_estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password_estudiante, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password_estudiante, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Iniciar sesion" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Views/Accounts/RegistroMaterias.cshtml
@model Projecto1.Models.Materias

<html>
<head>
    <title>Registrar materias</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h4 {
            margin-top: 0;
            margin-bottom: 20px;
            color: #333;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #333;
        }

        .form-control {
            display: block;
            width: 100%;
            padding: 10px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            border-radius: 4px;
            transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
        }

            .form-control:focus {
                border-color: #66afe9;
                outline: 0;
                box-shadow: 0 0 8px rgba(102, 175, 233, 0.6);
            }

        .text-danger {
            color: red;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            margin-bottom: 0;
            font-size: 14px;
            font-weight: bold;
            line-height: 1.42857143;
            text-align: center;
            white-space: nowrap;
            vertical-align: middle;
            cursor: pointer;
            background-image: none;
            border: 1px solid transparent;
            border-radius: 4px;
        }

        .btn-default {
            color: #333;
            background-color: #fff;
            border-color: #ccc;
        }

            .btn-default:hover,
            .btn-default:focus,
            .btn-default:active {
                color: #333;
                background-color: #e6e6e6;
                border-color: #adadad;
            }
    </style>
</head>

@{
    string caracteres = "abcdefghijklmnopqrstuvwxyz0123456789";
    Random random = new Random();
    int longitud = random.Next(1, 6);
    string codigo1 = new string(Enumerable.Range(1, longitud)
        .Select(_ => caracteres[random.Next(caracteres.Length)])
        .Distinct()
        .ToArray());

    Console.WriteLine("Código aleatorio: " + codigo1);
}
@{
    ViewBag.Title = "Registrar materias";
}

@{

    var Materia = new List<SelectListItem>
    { 
      new SelectListItem { Value = "ASP.NET MVC", Text = "ASP.NET MVC" },
      new SelectListItem { Value = "C# CONSOLA", Text = "C# CONSOLA" },
      new SelectListItem { Value = "WINDOWS FORM", Text = "WINDOWS FORM" },
      new SelectListItem { Value = "ASP.NET ANGULAR", Text = "ASP.NET ANGULAR" },
      new SelectListItem { Value = "ASP.NET REACT", Text = "ASP.NET REACT" }
      

    };


    }

@{ 


    var Horario = new List<SelectListItem>
    {
      new SelectListItem { Value = "8:00 AM - 12: 00 PM", Text = "8:00 AM - 12: 00 PM" },
      new SelectListItem { Value = "1:00 PM - 3:00PM", Text = "1:00 PM - 3:00PM" },
      new SelectListItem { Value = "3:30 PM - 5:30 PM", Text = "3:30 PM - 5:30 PM" },
      new SelectListItem { Value = "6:00 PM - 8:00 PM", Text = "6:00 PM - 8:00 PM" },
      new SelectListItem { Value = "8:00 PM - 10:00 PM", Text = "8:00 PM - 10:00 PM" }

     };

}
<body>

    <h2>Registrar materia</h2>


    @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Materias</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.id_materia, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.id_materia, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", Value = @codigo1 } })
                            @Html.ValidationMessageFor(model => model.id_materia, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombres_estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombres_estudiante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombres_estudiante, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Apellidos_estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Apellidos_estudiante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Apellidos_estudiante, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Materia, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Materia, new SelectList(Materia, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Materia, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Hora, new SelectList(Horario, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Hora, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email_estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email_estudiante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email_estudiante, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Enviar" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Inicio</title>

</head>
<body>
    @{
        ViewBag.Title = "Inicio";
    }

    <div class="jumbotron">
        <h1>Bienvenido al curso de C# ASP.NET</h1>
        <p class="lead">
            ASP.NET es un framework de desarrollo web creado por Microsoft. Es una tecnología utilizada para construir aplicaciones web dinámicas y escalables. ASP.NET permite a los desarrolladores crear sitios web y aplicaciones utilizando múltiples lenguajes de programación, como C# o Visual Basic.NET.

        </p>
        <p><a href="~/Views/Accounts/Signup.cshtml" class="btn btn-primary btn-lg">Inscribete ahora!</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Sepa que</h2>
            <p>
                ASP.NET se basa en el Common Language Runtime (CLR), que es el entorno de ejecución de .NET Framework. Proporciona una amplia gama de características y funcionalidades que simplifican el desarrollo web, como el manejo de solicitudes y respuestas, el enrutamiento, la gestión de sesiones, la autenticación y autorización, la generación de páginas dinámicas y la conexión a bases de datos.


            </p>

        </div>
        <div class="col-md-4">
            <h2>Tambien...</h2>
            <p>
                ASP.NET se basa en el Common Language Runtime (CLR), que es el entorno de ejecución de .NET Framework. Proporciona una amplia gama de características y funcionalidades que simplifican el desarrollo web, como el manejo de solicitudes y respuestas, el enrutamiento, la gestión de sesiones, la autenticación y autorización, la generación de páginas dinámicas y la conexión a bases de datos.


            </p>
          
        </div>
        <div class="col-md-4">
            <h2>Por ultimo</h2>
            <p>Existen diferentes modelos de programación dentro de ASP.NET, como Web Forms, MVC (Model-View-Controller) y Web API. Web Forms utiliza un enfoque de arrastrar y soltar para crear interfaces de usuario y eventos de servidor para manejar interacciones. MVC divide la aplicación en tres componentes principales: el modelo (la lógica y los datos), la vista (la interfaz de usuario) y el controlador (maneja las interacciones y coordina el flujo de la aplicación). Web API se utiliza para construir servicios web y API RESTful.</p>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
@{ 
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @{
                        if (isLoggedIn)
                        {
                            <li>@Html.ActionLink(User.Identity.Name, "Index", "Home")</li>
                            <li>@Html.ActionLink("Signout", "Signout", "Accounts")</li>
                            <li>@Html.ActionLink("RegistroMaterias", "RegistroMaterias", "Accounts")</li>
                        }

                        else
                        {

                            <li>@Html.ActionLink("Login", "Login", "Accounts")</li>
                            <li>@Html.ActionLink("Register", "Signup", "Accounts")</li>



                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>